# Site settings
title: "William Menezes – Cybersecurity Portfolio"
description: "Portfólio profissional em Segurança da Informação | Professional Cybersecurity Portfolio"
author: "William Menezes"

# URL base (GitHub Pages gera automaticamente)
baseurl: "/portfolio-seguranca" # Adiciona o nome do repositório como base
url: "https://wdickson11.github.io"

# Theme (escolha entre: minimal, cayman, slate, merlot, etc.)
# 1. Configurações do Tema Remoto
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme

# Navegação personalizada
navbar:
  - name: "Home"
    link: "/"
  - name: "Português 🇧🇷"
    link: "{{ site.baseurl }}/pt/"
  - name: "English 🇺🇸"
    link: "{{ site.baseurl }}/en/"
  - name: "Projects"
    link: "{{ site.baseurl }}/projects/"
  - name: "Reports"
    link: "{{ site.baseurl }}/projects/reports/"

# Social links (opcional)
social_links:
  linkedin: "https://www.linkedin.com/in/williamdmenezes"
  github: "https://github.com/Wdickson11"
  email: "will.menezes@pm.me"
